--[[
ATCAI - atc_core.lua
Core ATC state machine, DCS World API queries, and phraseology. No menu/input handling
here — see lua/atc/atc_menu.lua for how players trigger these functions.

Load order matters: this file must be loaded before atc_menu.lua.

The pure helpers (wind/runway/formatting) take plain data rather than DCS objects so
they can be unit-tested outside the sim — see tools/test_atc_core.lua.
]]

ATC = ATC or {}
ATC.state = ATC.state or {}
ATC.METRES_PER_NAUTICAL_MILE = 1852

-- Where these scripts live, so siblings and the voice inbox can be found without the
-- mission having to inject absolute paths. DCS doesn't sanitise `debug`, and this keeps
-- missions built before a script was added from silently missing it.
local function scriptDirectory()
    -- Must not be wrapped in pcall: that adds a stack frame, so level 1 would resolve
    -- to pcall's C frame rather than this function's own chunk.
    if type(debug) ~= "table" or type(debug.getinfo) ~= "function" then
        return nil
    end
    local info = debug.getinfo(1, "S")
    if not info or not info.source then
        return nil
    end
    return (tostring(info.source):gsub("^@", "")):match("^(.*[\\/])")
end

ATCAI_SCRIPT_DIR = ATCAI_SCRIPT_DIR or scriptDirectory()
if ATCAI_SCRIPT_DIR then
    ATCAI_INBOX_PATH = ATCAI_INBOX_PATH or (ATCAI_SCRIPT_DIR .. "inbox.lua")
    ATCAI_CONFIG_PATH = ATCAI_CONFIG_PATH or (ATCAI_SCRIPT_DIR .. "config.lua")
end

-- User settings are applied BEFORE the defaults below, which are all written as
-- "keep what's there, otherwise use this" — so a configured value survives and an
-- absent one falls back. That keeps load order from mattering.
if not ATC.applyConfig and ATCAI_SCRIPT_DIR then
    pcall(dofile, ATCAI_SCRIPT_DIR .. "atc_config.lua")
end
if ATC.loadConfig then
    ATC.loadConfig(ATCAI_CONFIG_PATH)
end

-- Real per-airfield frequencies, generated by the manager from the game's own terrain
-- files. Absent (hand install, or DCS not found) just means the fixed list below is used.
if ATCAI_SCRIPT_DIR then
    pcall(dofile, ATCAI_SCRIPT_DIR .. "frequencies.lua")
end

-- How close you must be for a field to answer. Ground operations want a tight radius so
-- "your" airfield is unambiguously the one you're sitting on; airborne calls are made
-- from far further out, so inbound reports need a much wider net.
ATC.AIRBASE_SEARCH_RADIUS = ATC.AIRBASE_SEARCH_RADIUS or 6000     -- metres, on the ground (~3 nm)
ATC.AIRBASE_AIR_RADIUS = ATC.AIRBASE_AIR_RADIUS or 92600          -- metres, airborne (50 nm)

-- 276.375 is the F-15C's default UHF preset (CHAN 06) in the test mission; the rest are
-- common DCS defaults. If you don't hear ATC, check the frequency on your radio and add
-- it here — the two lists must stay the same length.
ATC.TTS_FREQUENCY = ATC.TTS_FREQUENCY or "276.375,251.0,305.0,124.0,127.5"
ATC.TTS_MODULATION = ATC.TTS_MODULATION or "AM,AM,AM,AM,AM"

-- Flight phases, in the order a sortie normally moves through them.
ATC.PHASE = {
    PARKED = "parked",
    STARTUP = "startup",
    HOLDING_SHORT = "holding_short",
    TAKEOFF = "takeoff_cleared",
    AIRBORNE = "airborne",
    INBOUND = "inbound",
    LANDING = "cleared_to_land",
}

-- ---------- pure helpers ----------

local function normalizeHeading(deg)
    deg = deg % 360
    if deg < 0 then
        deg = deg + 360
    end
    return deg
end

-- Runway designators are magnetic heading / 10, with 36 rather than 0 for north.
function ATC.headingToRunwayName(heading)
    local num = math.floor(normalizeHeading(heading) / 10 + 0.5)
    if num == 0 then
        num = 36
    elseif num > 36 then
        num = num - 36
    end
    return string.format("%02d", num)
end

-- DCS wind vectors point the way the air is moving; aviation quotes the direction it
-- comes FROM. x is north, z is east. Returns (degrees-from, knots).
function ATC.windFromVector(wind)
    if not wind then
        return 0, 0
    end
    local speedMs = math.sqrt((wind.x or 0) ^ 2 + (wind.z or 0) ^ 2)
    local towardDeg = math.deg(math.atan2(wind.z or 0, wind.x or 0))
    return normalizeHeading(towardDeg + 180), speedMs * 1.94384
end

-- A physical runway serves two opposing ends; ATC picks whichever suits the wind.
function ATC.runwayEnds(runway)
    local ends = {}
    if not runway then
        return ends
    end

    local name = tostring(runway.Name or runway.name or "")
    local digits = name:match("^%s*(%d+)")
    local num = tonumber(digits)
    if num and num >= 1 and num <= 36 then
        local recip = num + 18
        if recip > 36 then
            recip = recip - 36
        end
        ends[1] = { name = string.format("%02d", num), heading = normalizeHeading(num * 10) }
        ends[2] = { name = string.format("%02d", recip), heading = normalizeHeading(recip * 10) }
        return ends
    end

    -- Name wasn't a designator, so fall back to the reported course (radians).
    if runway.course then
        local heading = normalizeHeading(-math.deg(runway.course))
        local recip = normalizeHeading(heading + 180)
        ends[1] = { name = ATC.headingToRunwayName(heading), heading = heading }
        ends[2] = { name = ATC.headingToRunwayName(recip), heading = recip }
    end
    return ends
end

-- Picks the end with the strongest headwind component.
function ATC.selectRunwayEnd(runways, windFromDeg)
    local best, bestScore
    for _, runway in ipairs(runways or {}) do
        for _, candidate in ipairs(ATC.runwayEnds(runway)) do
            local score = math.cos(math.rad(candidate.heading - windFromDeg))
            if not bestScore or score > bestScore then
                best, bestScore = candidate, score
            end
        end
    end
    return best
end

function ATC.formatWind(fromDeg, speedKts)
    if not speedKts or speedKts < 1 then
        return "wind calm"
    end
    return string.format("wind %03d at %d", math.floor(fromDeg + 0.5), math.floor(speedKts + 0.5))
end

-- ATIS broadcasts are lettered so a pilot and controller can confirm they're working
-- from the same information. The letter advances each hour of mission time.
ATC.PHONETIC = {
    "Alpha", "Bravo", "Charlie", "Delta", "Echo", "Foxtrot", "Golf", "Hotel",
    "India", "Juliett", "Kilo", "Lima", "Mike", "November", "Oscar", "Papa",
    "Quebec", "Romeo", "Sierra", "Tango", "Uniform", "Victor", "Whiskey",
    "X-ray", "Yankee", "Zulu",
}

function ATC.informationLetter(secondsSinceMidnight)
    local hours = math.floor((tonumber(secondsSinceMidnight) or 0) / 3600)
    return ATC.PHONETIC[(hours % 26) + 1]
end

function ATC.formatClock(secondsSinceMidnight)
    local total = math.floor((tonumber(secondsSinceMidnight) or 0) / 60)
    return string.format("%02d%02d", math.floor(total / 60) % 24, total % 60)
end

function ATC.formatTemperature(celsius)
    if not celsius then
        return "temperature unavailable"
    end
    local rounded = math.floor(celsius + 0.5)
    if rounded < 0 then
        return string.format("temperature minus %d", math.abs(rounded))
    end
    return string.format("temperature %d", rounded)
end

-- Bearing FROM one point TO another. x is north, z is east, same as the wind vector.
-- This is a TRUE bearing: the scripting API exposes no magnetic variation, so on a map
-- with significant declination it will differ from what the aircraft's compass reads.
-- Runway designators come from DCS already magnetic, so the two are not interchangeable.
function ATC.bearingBetween(from, to)
    if not from or not to then
        return nil
    end
    local dx = (to.x or 0) - (from.x or 0)
    local dz = (to.z or 0) - (from.z or 0)
    if dx == 0 and dz == 0 then
        return nil
    end
    return normalizeHeading(math.deg(math.atan2(dz, dx)))
end

function ATC.headingText(degrees)
    if not degrees then
        return "unknown"
    end
    -- Round first, then wrap: 359.6 is heading 360, which is spoken as 000, not "360".
    return string.format("%03d", math.floor(normalizeHeading(degrees) + 0.5) % 360)
end

function ATC.distanceText(metres)
    if not metres then
        return "position unknown"
    end
    local miles = metres / ATC.METRES_PER_NAUTICAL_MILE
    if miles < 1 then
        return "overhead the field"
    end
    return string.format("%d miles", math.floor(miles + 0.5))
end

function ATC.formatQNH(pressurePa)
    if not pressurePa or pressurePa <= 0 then
        return "QNH unavailable"
    end
    return string.format("QNH %.2f", pressurePa / 3386.389)
end

-- Unit names carry Mission Editor decoration ("- Chevy 81 (Player)") that reads badly
-- over TTS. Reduce to just the callsign.
function ATC.callsign(unit)
    local raw = unit:getName() or "Unknown"
    local name = raw:gsub("%b()", ""):gsub("^[%s%-%*#]+", ""):gsub("[%s%-]+$", "")
    if name == "" then
        return raw
    end
    return name
end

-- ---------- state ----------

function ATC.getState(unitName)
    if not ATC.state[unitName] then
        ATC.state[unitName] = { phase = ATC.PHASE.PARKED }
    end
    return ATC.state[unitName]
end

-- ---------- DCS-facing lookups ----------

local function get2DDistance(p1, p2)
    local dx = p1.x - p2.x
    local dz = p1.z - p2.z
    return math.sqrt(dx * dx + dz * dz)
end

-- Nearest airbase at any distance, optionally restricted by a filter. Separated out
-- because a pilot in trouble needs an answer from beyond normal ATC range, where
-- findNearestAirbase deliberately refuses.
local function scanAirbases(unit, accept)
    local unitPos = unit:getPoint()
    local nearest, nearestDist = nil, math.huge

    for _, airbase in pairs(world.getAirbases()) do
        if not accept or accept(airbase) then
            local dist = get2DDistance(unitPos, airbase:getPoint())
            if dist < nearestDist then
                nearest, nearestDist = airbase, dist
            end
        end
    end
    return nearest, nearestDist
end

function ATC.findNearestAirbase(unit)
    local nearest, nearestDist = scanAirbases(unit)

    local limit = ATC.AIRBASE_SEARCH_RADIUS
    if unit.inAir and unit:inAir() then
        limit = ATC.AIRBASE_AIR_RADIUS
    end

    if nearest and nearestDist <= limit then
        return nearest, nearestDist
    end
    -- Hand back the distance even on a miss, so the refusal can say how far out you are.
    return nil, nearestDist
end

-- Somewhere the player could actually put down: their own coalition's, or neutral.
-- A field whose coalition can't be read is offered anyway - guessing wrong here means
-- withholding a runway from someone who needs one, which is the worse failure.
function ATC.usableByCoalition(airbase, side)
    if not side or not airbase or type(airbase.getCoalition) ~= "function" then
        return true
    end
    local ok, airbaseSide = pcall(airbase.getCoalition, airbase)
    if not ok or airbaseSide == nil then
        return true
    end
    local neutral = (coalition and coalition.side and coalition.side.NEUTRAL) or 0
    return airbaseSide == side or airbaseSide == neutral
end

-- The field to divert to: nearest friendly one at any distance, with the bearing to it.
function ATC.findDivertField(unit)
    local side
    if type(unit.getCoalition) == "function" then
        local ok, value = pcall(unit.getCoalition, unit)
        if ok then side = value end
    end

    local airbase, distance = scanAirbases(unit, function(candidate)
        return ATC.usableByCoalition(candidate, side)
    end)
    if not airbase then
        return nil
    end
    return airbase, distance, ATC.bearingBetween(unit:getPoint(), airbase:getPoint())
end

-- Wind, altimeter and the runway in use, as reported by the field.
function ATC.getFieldConditions(airbase)
    local point = airbase:getPoint()
    -- Sample wind slightly above the surface; at ground level DCS reports zero.
    local windPoint = { x = point.x, y = (point.y or 0) + 10, z = point.z }
    local windFrom, windKts = ATC.windFromVector(atmosphere.getWind(windPoint))
    local temperature, pressure = atmosphere.getTemperatureAndPressure(point)

    return {
        windFrom = windFrom,
        windKts = windKts,
        windText = ATC.formatWind(windFrom, windKts),
        qnhText = ATC.formatQNH(pressure),
        celsius = temperature and (temperature - 273.15) or nil,
        runway = ATC.selectRunwayEnd(airbase:getRunways(), windFrom),
    }
end

function ATC.towerName(airbase)
    return airbase:getCallsign() or airbase:getName()
end

local function runwayText(conditions)
    if conditions.runway then
        return "runway " .. conditions.runway.name
    end
    return "the active runway"
end

-- The frequencies this field actually uses, as SRS wants them: two matching
-- comma-separated lists. Falls back to the configured list when the field is unknown.
function ATC.fieldFrequencies(airbase)
    if type(ATCAI_FREQUENCIES) ~= "table" or not airbase then
        return ATC.TTS_FREQUENCY, ATC.TTS_MODULATION
    end

    -- Built up rather than declared inline: a nil callsign would end an ipairs table
    -- early and the name would never be tried.
    local names = {}
    if airbase.getCallsign then
        local callsign = airbase:getCallsign()
        if callsign then table.insert(names, callsign) end
    end
    if airbase.getName then
        local name = airbase:getName()
        if name then table.insert(names, name) end
    end

    local entry
    for _, name in ipairs(names) do
        entry = entry or ATCAI_FREQUENCIES[tostring(name):lower()]
    end
    if not entry or #entry == 0 then
        return ATC.TTS_FREQUENCY, ATC.TTS_MODULATION
    end

    local freqs, modes = {}, {}
    for _, channel in ipairs(entry) do
        table.insert(freqs, string.format("%.3f", channel.mhz))
        table.insert(modes, channel.modulation or "AM")
    end
    return table.concat(freqs, ","), table.concat(modes, ",")
end

-- Some replies have to reach you wherever you are and whatever you're tuned to: a
-- refusal, your own loadout, and anything said during an emergency. Transmitting those
-- on one field's frequency is self-defeating - the calls that matter most when you're
-- away from a field would go out on the one frequency you're least likely to be on.
-- So they go out on the field's frequencies AND the configured fallback list at once.
function ATC.wideFrequencies(airbase)
    local freqs, modes = {}, {}
    local seen = {}

    local function add(freqList, modeList)
        local f, m = {}, {}
        for value in tostring(freqList):gmatch("[^,]+") do table.insert(f, value) end
        for value in tostring(modeList):gmatch("[^,]+") do table.insert(m, value) end
        for i, value in ipairs(f) do
            local key = tostring(tonumber(value) or value)
            if not seen[key] then
                seen[key] = true
                table.insert(freqs, value)
                table.insert(modes, m[i] or m[#m] or "AM")
            end
        end
    end

    if airbase then
        add(ATC.fieldFrequencies(airbase))
    end
    add(ATC.TTS_FREQUENCY, ATC.TTS_MODULATION)
    return table.concat(freqs, ","), table.concat(modes, ",")
end

local function say(groupId, text, airbase, wide)
    trigger.action.outTextForGroup(groupId, text, 15, false)
    -- Mission Lua can't launch processes or write files, so dcs.log is the outbound
    -- channel: voice-bridge/atcai_tts.py tails it for this prefix and speaks the line
    -- over SRS.
    local freqs, modes
    if wide then
        freqs, modes = ATC.wideFrequencies(airbase)
    else
        freqs, modes = ATC.fieldFrequencies(airbase)
    end
    env.info(string.format("ATCAI_TTS|%s|%s|%s", tostring(freqs), tostring(modes), text))
end

-- ---------- request plumbing ----------

-- Resolves the common preamble every request needs, or explains why it can't proceed.
-- Speaks the refusal itself and returns nil when the request doesn't fit the situation.
local function begin(params, opts)
    local unit = params.unit
    local callsign = ATC.callsign(unit)
    local state = ATC.getState(unit:getName())
    local airborne = unit:inAir()

    -- Refusals always go out wide. A reply explaining why ATC can't help you is exactly
    -- the one you cannot afford to miss, and the situations that produce it are the
    -- situations where you're least likely to be tuned to the right field.
    local function refuse(text, airbase)
        say(params.groupId, text, airbase, true)
        return nil
    end

    if opts.requireAirborne and not airborne then
        return refuse(string.format("%s, unable, you're still on the ground.", callsign))
    end
    if opts.requireGround and airborne then
        return refuse(string.format("%s, unable, you're airborne.", callsign))
    end

    if opts.phases then
        local allowed = false
        for _, phase in ipairs(opts.phases) do
            if state.phase == phase then
                allowed = true
                break
            end
        end
        if not allowed then
            return refuse(string.format("%s, unable, %s", callsign, opts.denial))
        end
    end

    local airbase, distance = ATC.findNearestAirbase(unit)
    if not airbase and opts.anyDistance then
        -- An emergency call is answered from wherever it's made; a field out of normal
        -- range still owns the problem rather than leaving the pilot talking to nobody.
        airbase, distance = ATC.findDivertField(unit)
    end
    if not airbase then
        -- Out of range, so there's no field frequency to use - but the nearest one is
        -- still the likeliest thing the player is tuned to, so include it.
        local nearest = ATC.findDivertField(unit)
        if distance and distance < math.huge then
            return refuse(string.format("%s, no ATC in range, nearest field is %d miles.",
                callsign, math.floor(distance / ATC.METRES_PER_NAUTICAL_MILE + 0.5)),
                nearest)
        end
        return refuse(string.format("%s, no ATC in range.", callsign), nearest)
    end

    local ctx = {
        unit = unit,
        callsign = callsign,
        state = state,
        airbase = airbase,
        distance = distance,
        tower = ATC.towerName(airbase),
        conditions = ATC.getFieldConditions(airbase),
    }
    ctx.say = function(text) say(params.groupId, text, airbase, opts.wide) end
    return ctx
end

-- A spoken ATIS: what you'd hear on a real field's recorded broadcast, minus the
-- visibility and cloud detail DCS doesn't expose to scripts.
function ATC.atisReport(towerName, conditions, secondsSinceMidnight)
    local letter = ATC.informationLetter(secondsSinceMidnight)
    local runway = conditions.runway and ("runway " .. conditions.runway.name)
                   or "the active runway"
    return string.format(
        "%s information %s, time %s. %s in use. %s. %s. %s. Advise on initial contact "
        .. "you have information %s.",
        towerName, letter, ATC.formatClock(secondsSinceMidnight), runway,
        conditions.windText, ATC.formatTemperature(conditions.celsius),
        conditions.qnhText, letter)
end

-- Traffic checking lives in atc_traffic.lua. If that file isn't loaded, clearances carry
-- on without it rather than failing.
function ATC.checkRunway(ctx)
    if type(ATC.runwayConflict) ~= "function" then
        return nil
    end
    local ok, conflict = pcall(ATC.runwayConflict, ctx.airbase, ctx.conditions, ctx.unit)
    if not ok then
        env.info("ATCAI: traffic check failed: " .. tostring(conflict))
        return nil
    end
    return conflict
end

-- ---------- requests ----------

function ATC.requestRadioCheck(params)
    local ctx = begin(params, {})
    if not ctx then return end
    ctx.say(string.format("%s, %s, read you five by five.", ctx.callsign, ctx.tower))
end

function ATC.requestStartup(params)
    local ctx = begin(params, {
        requireGround = true,
        phases = { ATC.PHASE.PARKED },
        denial = "you've already started up.",
    })
    if not ctx then return end

    ctx.state.phase = ATC.PHASE.STARTUP
    ctx.say(string.format("%s, %s, startup approved, %s in use, %s, %s.",
        ctx.callsign, ctx.tower, runwayText(ctx.conditions),
        ctx.conditions.windText, ctx.conditions.qnhText))
end

function ATC.requestTaxi(params)
    local ctx = begin(params, {
        requireGround = true,
        phases = { ATC.PHASE.PARKED, ATC.PHASE.STARTUP },
        denial = "you're already taxiing.",
    })
    if not ctx then return end

    ctx.state.phase = ATC.PHASE.HOLDING_SHORT
    ctx.say(string.format("%s, %s, taxi to holding point %s, %s, hold short.",
        ctx.callsign, ctx.tower, runwayText(ctx.conditions), ctx.conditions.qnhText))
end

function ATC.requestTakeoff(params)
    local ctx = begin(params, {
        requireGround = true,
        phases = { ATC.PHASE.HOLDING_SHORT, ATC.PHASE.TAKEOFF },
        denial = "request taxi first.",
    })
    if not ctx then return end

    local conflict = ATC.checkRunway(ctx)
    if conflict then
        -- Stay at the holding point: the phase is deliberately left alone so the pilot
        -- can simply ask again once the runway clears.
        if conflict.kind == "runway" then
            ctx.say(string.format("%s, %s, hold position, traffic on the runway.",
                ctx.callsign, ctx.tower))
        else
            ctx.say(string.format("%s, %s, hold short, landing traffic %s.",
                ctx.callsign, ctx.tower, ATC.distanceText(conflict.distance)))
        end
        return
    end

    ctx.state.phase = ATC.PHASE.TAKEOFF
    ctx.say(string.format("%s, %s, %s, %s, cleared for takeoff.",
        ctx.callsign, ctx.tower, runwayText(ctx.conditions), ctx.conditions.windText))
end

function ATC.requestInbound(params)
    local ctx = begin(params, { requireAirborne = true })
    if not ctx then return end

    ctx.state.phase = ATC.PHASE.INBOUND
    ctx.say(string.format("%s, %s, %s, join the circuit for %s, %s, %s, report final.",
        ctx.callsign, ctx.tower, ATC.distanceText(ctx.distance), runwayText(ctx.conditions),
        ctx.conditions.windText, ctx.conditions.qnhText))
end

function ATC.requestLanding(params)
    local ctx = begin(params, { requireAirborne = true })
    if not ctx then return end

    -- A declared emergency is never sent around and never sequenced behind anyone;
    -- the traffic in the way is the traffic that gets moved.
    local conflict
    if not ctx.state.emergency then
        conflict = ATC.checkRunway(ctx)
    end
    if conflict then
        ctx.state.phase = ATC.PHASE.INBOUND
        if conflict.kind == "runway" then
            ctx.say(string.format("%s, %s, go around, traffic on the runway.",
                ctx.callsign, ctx.tower))
        else
            ctx.say(string.format(
                "%s, %s, continue approach, number two behind the %s, %s ahead.",
                ctx.callsign, ctx.tower, conflict.typeName,
                ATC.distanceText(conflict.distance)))
        end
        return
    end

    ctx.state.phase = ATC.PHASE.LANDING
    if ctx.state.emergency then
        ctx.say(string.format(
            "%s, %s, %s, %s, cleared to land, you have priority, emergency vehicles "
            .. "standing by.",
            ctx.callsign, ctx.tower, runwayText(ctx.conditions), ctx.conditions.windText))
        return
    end
    ctx.say(string.format("%s, %s, %s, %s, cleared to land.",
        ctx.callsign, ctx.tower, runwayText(ctx.conditions), ctx.conditions.windText))
end

-- ---------- emergencies ----------

-- Declaring puts the aircraft at the front of the queue until it's parked. Everything
-- that would normally hold it - sequencing, phase order, being outside ATC range - gives
-- way, which is the whole point of the call.
function ATC.declareEmergency(params)
    local ctx = begin(params, { anyDistance = true, wide = true })
    if not ctx then return end

    ctx.state.emergency = true

    if not ctx.unit:inAir() then
        ctx.say(string.format(
            "%s, %s, roger your emergency, shut down where you are, emergency services "
            .. "are on the way.", ctx.callsign, ctx.tower))
        return
    end

    -- Airborne: hand them a runway immediately rather than making them ask again.
    ctx.state.phase = ATC.PHASE.INBOUND
    local bearing = ATC.bearingBetween(ctx.unit:getPoint(), ctx.airbase:getPoint())
    local steer = bearing and string.format("steer %s, ", ATC.headingText(bearing)) or ""

    ctx.say(string.format(
        "%s, %s, roger your emergency, %s%s, %s in use, %s, %s. You have priority, "
        .. "cleared to land, emergency vehicles standing by.",
        ctx.callsign, ctx.tower, steer, ATC.distanceText(ctx.distance),
        runwayText(ctx.conditions), ctx.conditions.windText, ctx.conditions.qnhText))
end

-- Where to go when you no longer know, or the field you came from isn't an option.
-- Answers at any range: being out of ATC range is the situation this call exists for.
function ATC.requestVectors(params)
    local ctx = begin(params, { requireAirborne = true, anyDistance = true, wide = true })
    if not ctx then return end

    local field, distance, bearing = ATC.findDivertField(ctx.unit)
    if not field then
        ctx.say(string.format("%s, %s, no friendly field found.", ctx.callsign, ctx.tower))
        return
    end

    local name = ATC.towerName(field)
    if not bearing then
        ctx.say(string.format("%s, %s, you're overhead %s.", ctx.callsign, ctx.tower, name))
        return
    end

    ctx.say(string.format("%s, %s, nearest friendly field is %s, steer %s, %s.",
        ctx.callsign, ctx.tower, name, ATC.headingText(bearing),
        ATC.distanceText(distance)))
end

-- Skipping the circuit, for when flying a full pattern isn't realistic.
function ATC.requestStraightIn(params)
    local ctx = begin(params, { requireAirborne = true })
    if not ctx then return end

    ctx.state.phase = ATC.PHASE.INBOUND
    ctx.state.straightIn = true

    local conflict = ATC.checkRunway(ctx)
    if conflict and not ctx.state.emergency then
        ctx.say(string.format(
            "%s, %s, straight-in approved for %s, expect delay, traffic %s ahead.",
            ctx.callsign, ctx.tower, runwayText(ctx.conditions),
            ATC.distanceText(conflict.distance)))
        return
    end

    ctx.say(string.format("%s, %s, cleared straight-in approach %s, %s, %s, report final.",
        ctx.callsign, ctx.tower, runwayText(ctx.conditions), ctx.conditions.windText,
        ctx.conditions.qnhText))
end

function ATC.requestParking(params)
    local ctx = begin(params, {
        requireGround = true,
        phases = { ATC.PHASE.LANDING, ATC.PHASE.INBOUND, ATC.PHASE.TAKEOFF },
        denial = "you haven't landed.",
    })
    if not ctx then return end

    local wasEmergency = ctx.state.emergency
    ctx.state.phase = ATC.PHASE.PARKED
    ctx.state.emergency = false
    ctx.state.straightIn = false

    if wasEmergency then
        ctx.say(string.format(
            "%s, %s, vacate the runway and taxi to parking, emergency services are "
            .. "meeting you there.", ctx.callsign, ctx.tower))
        return
    end
    ctx.say(string.format("%s, %s, vacate the runway and taxi to parking.",
        ctx.callsign, ctx.tower))
end

function ATC.requestATIS(params)
    local ctx = begin(params, {})
    if not ctx then return end

    local clock = (timer and timer.getAbsTime) and timer.getAbsTime() or 0
    ctx.say(ATC.atisReport(ctx.tower, ctx.conditions, clock))
end

function ATC.requestLoadout(params)
    -- Your own aircraft reporting its own stores: no tower is involved, so this is never
    -- refused for range and always goes out wide. It used to run through the standard
    -- preamble, which meant flying beyond ATC range turned a question about your own
    -- pylons into "no ATC in range" - on a frequency you weren't tuned to, so all you
    -- saw was the on-screen text.
    local unit = params.unit
    local callsign = ATC.callsign(unit)
    local airbase = ATC.findDivertField(unit)
    local ammo = unit:getAmmo()

    local text
    if not ammo or #ammo == 0 then
        text = string.format("%s, no stores remaining.", callsign)
    else
        local parts = {}
        for _, item in ipairs(ammo) do
            local name = item.desc and (item.desc.displayName or item.desc.typeName)
                         or "unknown store"
            table.insert(parts, string.format("%d %s", item.count, name))
        end
        text = string.format("%s loadout: %s.", callsign, table.concat(parts, ", "))
    end

    say(params.groupId, text, airbase, true)
end

-- Load traffic awareness if the mission didn't list it explicitly, the same way
-- atc_menu.lua picks up the voice inbox.
if not ATC.runwayConflict and ATCAI_SCRIPT_DIR then
    local ok, err = pcall(dofile, ATCAI_SCRIPT_DIR .. "atc_traffic.lua")
    if not ok then
        env.info("ATCAI: could not auto-load atc_traffic.lua: " .. tostring(err))
    end
end

env.info("ATCAI: atc_core.lua loaded")
